"""Regenerates src/data/world-dots.ts: a dotted land map on an equirectangular
projection, plus the plant and every export destination in the same units.

    python3 scripts/dotmap.py path/to/ne_110m_land.geojson

Land data: Natural Earth 1:110m land polygons (public domain), e.g.
https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson
Needs Pillow."""
import json, sys
from PIL import Image, ImageDraw

LON = (-135.0, 112.0)   # west edge: Vancouver; east edge: past Bhutan
LAT = (-42.0, 66.0)     # south: Cape; north: Canada
SPACING = 1.55          # degrees between dots along a row
PPD = 20                # raster pixels per degree for the land test

ORIGIN = ("Bahadurgarh", 28.69, 76.93)
DESTINATIONS = [
    # country, city, region, lat, lon
    ("Qatar", None, "Middle East", 25.29, 51.53),
    ("UAE", None, "Middle East", 25.20, 55.27),
    ("Nepal", None, "South Asia", 27.72, 85.32),
    ("Bhutan", None, "South Asia", 27.47, 89.64),
    ("Kenya", None, "Africa", -1.29, 36.82),
    ("Tanzania", None, "Africa", -6.79, 39.28),
    ("Zambia", None, "Africa", -15.39, 28.32),
    ("Nigeria", None, "Africa", 6.52, 3.38),
    ("United Kingdom", None, "Europe", 51.51, -0.13),
    ("Germany", None, "Europe", 50.11, 8.68),
    ("United States", "New York", "North America", 40.71, -74.01),
    ("United States", "Los Angeles", "North America", 34.05, -118.24),
    ("Canada", "Toronto", "North America", 43.65, -79.38),
    ("Canada", "Vancouver", "North America", 49.28, -123.12),
]

def project(lat, lon):
    return round(lon - LON[0], 2), round(LAT[1] - lat, 2)

def main(path):
    geo = json.load(open(path))
    W, H = LON[1] - LON[0], LAT[1] - LAT[0]
    img = Image.new("1", (int(W * PPD), int(H * PPD)), 0)
    draw = ImageDraw.Draw(img)
    for f in geo["features"]:
        rings = f["geometry"]["coordinates"]
        if f["geometry"]["type"] == "MultiPolygon":
            rings = [r for poly in rings for r in poly]
        for ring in rings:
            pts = [((lon - LON[0]) * PPD, (LAT[1] - lat) * PPD) for lon, lat in ring]
            if len(pts) > 2:
                draw.polygon(pts, fill=1)
    px = img.load()
    dots, row, y = [], 0, SPACING / 2
    while y < H:
        x = SPACING / 2 + (SPACING / 2 if row % 2 else 0)
        while x < W:
            ix, iy = int(x * PPD), int(y * PPD)
            if 0 <= ix < img.width and 0 <= iy < img.height and px[ix, iy]:
                dots.append(f"M{x:.2f} {y:.2f}h.01")
            x += SPACING
        y += SPACING * 0.87
        row += 1
    ox, oy = project(ORIGIN[1], ORIGIN[2])
    dests = [
        dict(name=f"{c}, {city}" if city else c, country=c, city=city, region=r, x=project(la, lo)[0], y=project(la, lo)[1])
        for c, city, r, la, lo in DESTINATIONS
    ]
    out = (
        "/* Generated by scripts/dotmap.py from Natural Earth 1:110m land data:\n"
        "   an equirectangular dot grid from the Americas to South Asia. The plant\n"
        "   and every destination share the projection. Do not edit by hand. */\n"
        "export const worldMap = {\n"
        f"  view: {{ w: {W:g}, h: {H:g} }},\n"
        f"  spacing: {SPACING},\n"
        f"  dots: \"{''.join(dots)}\",\n"
        f"  origin: {json.dumps(dict(name=ORIGIN[0], x=ox, y=oy))},\n"
        f"  destinations: {json.dumps(dests)},\n"
        "};\n"
    )
    open("src/data/world-dots.ts", "w").write(out)
    print(f"{len(dots)} dots, {len(dests)} destinations, view {W:g}x{H:g}")

if __name__ == "__main__":
    main(sys.argv[1])
